version: '3.8'
services:
  todo-frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/todos
  todo-backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/todos
  redis:
    image: redis:latest
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
  nginx:
    build:
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - todo-frontend
      - todo-backend