version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./todo-backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - todo-backend
      - todo-frontend

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/todos
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: